"""empty message

Revision ID: 04a282457dce
Revises: 11affd11640a
Create Date: 2025-11-04 09:36:24.311373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a282457dce'
down_revision = '11affd11640a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.drop_column('require_login')

    # ### end Alembic commands ###
