"""empty message

Revision ID: 073fac5f0bcf
Revises: 4f7e3f56ff79
Create Date: 2024-12-16 12:04:17.403165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073fac5f0bcf'
down_revision = '4f7e3f56ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_request_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_request_date')
        batch_op.drop_column('request_count')

    # ### end Alembic commands ###
