"""empty message

Revision ID: 11affd11640a
Revises: 5d493f6e1ef3
Create Date: 2025-11-04 09:20:04.540427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11affd11640a'
down_revision = '5d493f6e1ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ai_messages')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_roles', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ai_prompt_templates', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_prompt_templates', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('ai_model_configs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('allowed_roles')

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_ai_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tokens', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
