"""empty message

Revision ID: 185d692e4ca8
Revises: 1519a7232aa1
Create Date: 2025-01-17 18:54:38.363260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185d692e4ca8'
down_revision = '1519a7232aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
