"""empty message

Revision ID: 1f2bab947733
Revises: bbb39d0cba1c
Create Date: 2024-11-10 21:07:16.477890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2bab947733'
down_revision = 'bbb39d0cba1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
