"""empty message

Revision ID: 4034b7af30a5
Revises: 96f9e3d5ab71
Create Date: 2025-04-13 21:11:13.534511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4034b7af30a5'
down_revision = '96f9e3d5ab71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtype', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('qtype')

    # ### end Alembic commands ###
