"""empty message

Revision ID: 4f7e3f56ff79
Revises: 913f3640984f
Create Date: 2024-11-15 21:45:14.474461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7e3f56ff79'
down_revision = '913f3640984f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_id_material', type_='foreignkey')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_class_id_material', 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###
