"""empty message

Revision ID: 574000294904
Revises: 1f9996a16486
Create Date: 2025-01-05 11:59:56.548663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574000294904'
down_revision = '1f9996a16486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_user_id_Notice', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_Notice', type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
