"""empty message

Revision ID: 5d493f6e1ef3
Revises: a5bb6aa01304
Create Date: 2025-06-14 11:37:52.118731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d493f6e1ef3'
down_revision = 'a5bb6aa01304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index('idx_exam_score', ['exam_id', 'score'], unique=False)
        batch_op.create_index('idx_user_exam', ['user_id', 'exam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index('idx_user_exam')
        batch_op.drop_index('idx_exam_score')

    # ### end Alembic commands ###
