"""empty message

Revision ID: 73112fbb4e4e
Revises: f6d3b66ac2b9
Create Date: 2024-09-25 15:42:49.336460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73112fbb4e4e'
down_revision = 'f6d3b66ac2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usernick', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('usernick')

    # ### end Alembic commands ###
