"""empty message

Revision ID: 77dce8c8c611
Revises: 04a282457dce
Create Date: 2025-11-21 08:02:48.287642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dce8c8c611'
down_revision = '04a282457dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_in_records', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'sign_in_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_in_records', schema=None) as batch_op:
        batch_op.drop_index('idx_user_date')

    # ### end Alembic commands ###
