"""empty message

Revision ID: 913f3640984f
Revises: adf6805ff88d
Create Date: 2024-11-15 21:15:52.827212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913f3640984f'
down_revision = 'adf6805ff88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id_learningmaterial', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_learningmaterial', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
