"""empty message

Revision ID: 96f9e3d5ab71
Revises: ffc9530ab08f
Create Date: 2025-04-05 00:35:07.139141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f9e3d5ab71'
down_revision = 'ffc9530ab08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_in_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_signin', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_signin', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_in_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_signin', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_signin', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
