"""empty message

Revision ID: a5bb6aa01304
Revises: 25e7658f6495
Create Date: 2025-05-09 16:27:19.540205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bb6aa01304'
down_revision = '25e7658f6495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chongbuluo_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chongbuluo_url', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
