"""empty message

Revision ID: adf6805ff88d
Revises: e47e71b30e19
Create Date: 2024-11-13 17:01:52.942569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf6805ff88d'
down_revision = 'e47e71b30e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_class_id_material', 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_id_material', type_='foreignkey')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
