"""empty message

Revision ID: bc90098eeb0b
Revises: 
Create Date: 2024-05-26 18:41:33.563964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc90098eeb0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_class_id_user', 'classes', ['class_id'], ['id'])
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_class_id_user', type_='foreignkey')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
