"""empty message

Revision ID: cfaf37109d25
Revises: 185d692e4ca8
Create Date: 2025-01-25 11:49:27.035883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfaf37109d25'
down_revision = '185d692e4ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_readings', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
