"""empty message

Revision ID: f28f90e01092
Revises: 9123f64b4041
Create Date: 2024-12-27 20:34:49.283465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28f90e01092'
down_revision = '9123f64b4041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_routelog', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_routelog', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_routelog', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_routelog', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
