"""empty message

Revision ID: ffc9530ab08f
Revises: cfaf37109d25
Create Date: 2025-04-05 00:30:26.254817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc9530ab08f'
down_revision = 'cfaf37109d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
